<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>KeyboardLocker</AssemblyName>
    <RootNamespace>KeyboardLocker</RootNamespace>
    <Version>1.0.0.9</Version>
    <AssemblyVersion>1.0.0.9</AssemblyVersion>
    <FileVersion>1.0.0.9</FileVersion>
    <Copyright>Copyright (C) 2026 Bougli</Copyright>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
</Project>
